{
 "title": "SHEMS Overview",
 "tags": [
  "energy",
  "monitoring",
  "overview"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "userId",
    "label": "User ID",
    "query": "SELECT UserId as __value, Username as __text FROM Users"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Power Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\ndud.timestamp as time,\r\nSUM(dud.Power_Consmpt) as power \r\nFROM DeviceUtilData dud \r\nJOIN DeviceInfo di ON dud.DeviceId = di.DeviceId \r\nWHERE di.UserId in ('$userId') "
    }
   ]
  },
  {
   "title": "Total Energy Consumption - For $userId",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\ndud.timestamp as time,\r\nSUM(Energy) as Energy \r\nFROM DeviceUtilData dud \r\nJOIN DeviceInfo di ON dud.DeviceId = di.DeviceId \r\nWHERE di.UserId in ($userId) \r\nGROUP BY Timestamp;"
    }
   ]
  },
  {
   "title": "Power Consumption Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT Timestamp as time, \r\nSUM(Power_Consmpt) as power \r\nFROM DeviceUtilData dud \r\nJOIN DeviceInfo di ON dud.DeviceId = di.DeviceId \r\nWHERE di.UserId in ($userId) \r\nAND $__timeFilter(Timestamp) \r\nGROUP BY time \r\nORDER BY time"
    }
   ]
  }
 ]
}