{
 "title": "Power Analysis",
 "tags": [
  "energy",
  "monitoring",
  "power"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "userId",
    "label": "User ID",
    "query": "SELECT UserId as __value, Username as __text FROM Users"
   },
   {
    "name": "deviceType",
    "label": "Device Type",
    "query": "SELECT DISTINCT DeviceType as __text, DeviceType as __value FROM DeviceInfo WHERE UserId = $userId"
   }
  ]
 },
 "panels": [
  {
   "title": "Device Utilization",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "shems_db",
     "rawSql": "SELECT \r\nTimestamp as Time, \r\nSUM(dud.Power_Consmpt) as power,\r\ndi.DeviceType \r\n FROM DeviceUtilData dud \r\n JOIN DeviceInfo di ON dud.DeviceId = di.DeviceId \r\n WHERE di.UserId in ($userId) \r\n AND di.DeviceType in ($deviceType) \r\n AND $__timeFilter(Timestamp) \r\n GROUP BY di.DeviceType"
    }
   ]
  },
  {
   "title": "Power by Device Type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT di.DeviceType, \r\nSUM(dud.Power_Consmpt) as power\r\n FROM DeviceUtilData dud \r\n JOIN DeviceInfo di ON dud.DeviceId = di.DeviceId \r\n WHERE di.UserId in ($userId) \r\n AND $__timeFilter(Timestamp) \r\n GROUP BY di.DeviceType"
    }
   ]
  },
  {
   "title": "Power Consumption Trends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT Timestamp as time,\r\n DeviceName, \r\n Power_Consmpt as power \r\n FROM DeviceUtilData dud \r\n JOIN DeviceInfo di ON dud.DeviceId = di.DeviceId \r\n WHERE di.UserId in ($userId)\r\n  AND $__timeFilter(Timestamp) \r\n  ORDER BY time"
    }
   ]
  }
 ]
}